CREATE OR REPLACE FUNCTION private.is_workspace_member(_workspace_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.workspace_members m WHERE m.workspace_id = _workspace_id AND m.user_id = auth.uid()) $$;
REVOKE ALL ON FUNCTION private.is_workspace_member(uuid) FROM PUBLIC, anon;
GRANT USAGE ON SCHEMA private TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_workspace_member(uuid) TO authenticated;
DROP POLICY "members view workspace identity" ON public.workspaces;
CREATE POLICY "members view workspace identity" ON public.workspaces FOR SELECT TO authenticated USING (private.is_workspace_member(id));
DROP POLICY "team views projects" ON public.collaboration_projects;
CREATE POLICY "team views projects" ON public.collaboration_projects FOR SELECT TO authenticated USING (public.owns_workspace(workspace_id) OR private.is_workspace_member(workspace_id));
DROP POLICY "team views collaboration tasks" ON public.collaboration_tasks;
CREATE POLICY "team views collaboration tasks" ON public.collaboration_tasks FOR SELECT TO authenticated USING (public.owns_workspace(workspace_id) OR private.is_workspace_member(workspace_id));
DROP POLICY "team creates collaboration tasks" ON public.collaboration_tasks;
CREATE POLICY "team creates collaboration tasks" ON public.collaboration_tasks FOR INSERT TO authenticated WITH CHECK ((public.owns_workspace(workspace_id) OR private.is_workspace_member(workspace_id)) AND created_by = auth.uid() AND (assignee_id IS NULL OR assignee_id = (SELECT owner_id FROM public.workspaces WHERE id = workspace_id) OR EXISTS (SELECT 1 FROM public.workspace_members WHERE workspace_id = collaboration_tasks.workspace_id AND user_id = assignee_id)));
DROP POLICY "team edits collaboration tasks" ON public.collaboration_tasks;
CREATE POLICY "team edits collaboration tasks" ON public.collaboration_tasks FOR UPDATE TO authenticated USING (public.owns_workspace(workspace_id) OR private.is_workspace_member(workspace_id)) WITH CHECK ((public.owns_workspace(workspace_id) OR private.is_workspace_member(workspace_id)) AND (assignee_id IS NULL OR assignee_id = (SELECT owner_id FROM public.workspaces WHERE id = workspace_id) OR EXISTS (SELECT 1 FROM public.workspace_members WHERE workspace_id = collaboration_tasks.workspace_id AND user_id = assignee_id)));
DROP POLICY "owner or author deletes collaboration tasks" ON public.collaboration_tasks;
CREATE POLICY "owner or author deletes collaboration tasks" ON public.collaboration_tasks FOR DELETE TO authenticated USING (public.owns_workspace(workspace_id) OR (private.is_workspace_member(workspace_id) AND created_by = auth.uid()));
DROP FUNCTION public.is_workspace_member(uuid);
ALTER FUNCTION public.accept_workspace_invitation(text) SET SCHEMA private;
REVOKE ALL ON FUNCTION private.accept_workspace_invitation(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.accept_workspace_invitation(text) TO authenticated;
CREATE FUNCTION public.accept_workspace_invitation(_token_hash text) RETURNS uuid LANGUAGE sql SECURITY INVOKER SET search_path = public AS $$ SELECT private.accept_workspace_invitation(_token_hash) $$;
REVOKE ALL ON FUNCTION public.accept_workspace_invitation(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.accept_workspace_invitation(text) TO authenticated;